### ISSUE TITLE
Does not write the new Entry.

### ISSUE THREAD

**Issue by bassemolufda** [Elinvention/efibootmgr-gui#18] opened 2021-01-02 17:35 UTC
When i add a new Entry, i get this Error and it does not Write the new entry.

Command '['pkexec', 'sh', '-c', "efibootmgr --disk /dev/nvme0n1p --part 1 --create --label 'KUbuntu' --loader '\\EFI\\ubuntu\\shimx64.efi'\n"]' returned non-zero exit status 5.

sincelery Uwe

**Comment by Elinvention** [comment] 2021-01-03 16:36
I made some commits. Can you try them? Now it should also show the stderr of efibootmgr and that should give further insights of what's happening.
In the mean time you could also run this command: `sudo efibootmgr --disk /dev/nvme0n1p --part 1 --create --label 'KUbuntu' --loader '\EFI\ubuntu\shimx64.efi'`. Maybe pkexec doesn't grant the required permissions?

**Comment by Elinvention** [comment] 2021-02-08 11:40
Now that I look at it again, I think this issue is actually a duplicate of #10 and so it should have been resolved. You can reopen if the issue persist. Thanks.

**Closed by Elinvention** 2021-02-08 11:40 UTC
